before_script:
        - composer install --dev

stages:
        - build
        - deploy

build_doc:
        stage: build
        only:
                - tags
                - master
        script:
                - 'make doc'
        artifacts:
                paths: 
                        - doc/doxygen/

deploy_doc:
        stage: deploy
        only:
                - tags
                - master
        dependencies:
                - build_doc
        script:
                - 'echo "Destination: $DOC_INSTALL_DESTINATION/"'
                - 'test -n "$DOC_INSTALL_DESTINATION"'
                - '[ -d "$DOC_INSTALL_DESTINATION/$CI_BUILD_REF_NAME/" ] || mkdir -pv "$DOC_INSTALL_DESTINATION/$CI_BUILD_REF_NAME/"'
                - 'rsync -r --stats "./doc/doxygen/html/" "$DOC_INSTALL_DESTINATION/$CI_BUILD_REF_NAME/"'

