before_script:
        - composer install --dev

stages:
        - test
        - deploy

test:
        stage: test
        script:
                - 'make test'

doc:
        stage: deploy
        only:
                - tags
                - master
        script:
                - 'echo "Destination: $DOC_INSTALL_DESTINATION/"'
                - 'test -n "$DOC_INSTALL_DESTINATION"'
                - '[ -d "$DOC_INSTALL_DESTINATION/$CI_BUILD_REF_NAME/" ] || mkdir -pv "$DOC_INSTALL_DESTINATION/$CI_BUILD_REF_NAME/"'
                - 'make doc'
                - 'rsync -r --stats "./doc/doxygen/html/" "$DOC_INSTALL_DESTINATION/$CI_BUILD_REF_NAME/"'

